# Generated by Django 5.2 on 2026-03-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_voice_transcribe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField(blank=True)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='voices.voice')),
            ],
        ),
    ]
